import SwiftUI

struct ReportView: View {
    private let r = SteadiData.report

    var body: some View {
        ScrollView {
            VStack(spacing: 16) {
                header
                independenceOutcomes
                severityComparison
                sensorTable
                observations
                shareButtons
                Text("Report generated by STEADI · Sensor data from device STEADI-001")
                    .font(.system(size: 11))
                    .foregroundStyle(Color.muted)
                    .padding(.bottom, 24)
            }
            .padding(.horizontal, 16)
            .padding(.vertical, 12)
        }
        .background(Color.cream)
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(spacing: 6) {
                Image(systemName: "doc.text.fill")
                    .font(.system(size: 14))
                    .foregroundStyle(Color.coral)
                Text("CLINICAL REPORT")
                    .font(.system(size: 11, weight: .bold))
                    .tracking(1)
                    .foregroundStyle(Color.coral)
            }
            Text(r.patient)
                .font(.system(size: 24, weight: .heavy))
                .foregroundStyle(Color.ink)
            Text("\(r.condition) · Age \(r.age)")
                .font(.system(size: 13))
                .foregroundStyle(Color.muted)
            Text("Report period: \(r.period)")
                .font(.system(size: 12, weight: .semibold))
                .foregroundStyle(Color.ink.opacity(0.7))
                .padding(.top, 4)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(20)
        .brandCard()
    }

    // Spec §4 Tab 3 §2: independence outcomes FIRST, framed as clinical results
    private var independenceOutcomes: some View {
        VStack(spacing: 10) {
            HStack(spacing: 10) {
                MetricCard(label: "Independence regained", value: r.spillReduction + " fewer spills", highlight: true)
                MetricCard(label: "Meals eaten unassisted", value: "\(r.totalMeals)", highlight: true)
            }
            HStack(spacing: 10) {
                MetricCard(label: "Stability gain", value: "\(r.stabilityScoreStart) → \(r.stabilityScoreEnd)", highlight: true)
                MetricCard(label: "Device usage", value: r.deviceUsage, highlight: false)
            }
        }
    }

    private var severityComparison: some View {
        VStack(spacing: 12) {
            HStack(spacing: 12) {
                VStack(alignment: .leading, spacing: 2) {
                    Text("Baseline (Jul 8)").font(.system(size: 11, weight: .semibold)).foregroundStyle(Color.coral)
                    Text(r.avgSeverityStart).font(.system(size: 28, weight: .heavy)).foregroundStyle(Color.coral)
                    Text("Average tremor amplitude").font(.system(size: 10)).foregroundStyle(Color.muted)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(14)
                .background(Color.coral.opacity(0.06))
                .clipShape(RoundedRectangle(cornerRadius: 12))
                VStack(alignment: .leading, spacing: 2) {
                    Text("Latest (Aug 26)").font(.system(size: 11, weight: .semibold)).foregroundStyle(Color.teal)
                    Text(r.avgSeverityEnd).font(.system(size: 28, weight: .heavy)).foregroundStyle(Color.teal)
                    Text("Average tremor amplitude").font(.system(size: 10)).foregroundStyle(Color.muted)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(14)
                .background(Color.teal.opacity(0.06))
                .clipShape(RoundedRectangle(cornerRadius: 12))
            }
            StabilityChart(caption: "Tremor amplitude trending down; stability trending up.")
        }
    }

    private var sensorTable: some View {
        SectionCard(title: "Weekly sensor data") {
            VStack(spacing: 0) {
                HStack {
                    Text("Date").frame(maxWidth: .infinity, alignment: .leading)
                    Text("Amplitude").frame(maxWidth: .infinity, alignment: .trailing)
                    Text("Frequency").frame(maxWidth: .infinity, alignment: .trailing)
                    Text("Stability").frame(maxWidth: .infinity, alignment: .trailing)
                }
                .font(.system(size: 11, weight: .semibold))
                .foregroundStyle(Color.muted)
                .padding(.bottom, 6)
                ForEach(SteadiData.history) { row in
                    HStack {
                        Text(row.date).frame(maxWidth: .infinity, alignment: .leading)
                        Text(String(format: "%.1f", row.amplitude))
                            .foregroundStyle(amplitudeColor(row.amplitude))
                            .frame(maxWidth: .infinity, alignment: .trailing)
                        Text(String(format: "%.1f Hz", row.frequency))
                            .foregroundStyle(Color.ink)
                            .frame(maxWidth: .infinity, alignment: .trailing)
                        Text("\(row.stability)")
                            .font(.system(size: 12, weight: .bold))
                            .foregroundStyle(Color.teal)
                            .frame(maxWidth: .infinity, alignment: .trailing)
                    }
                    .font(.system(size: 12))
                    .padding(.vertical, 7)
                    Divider().overlay(Color.ink.opacity(0.05))
                }
            }
        }
    }

    private var observations: some View {
        SectionCard(title: "Clinical observations") {
            VStack(spacing: 8) {
                ForEach(Array(r.recommendations.enumerated()), id: \.offset) { _, rec in
                    HStack(alignment: .top, spacing: 10) {
                        Image(systemName: "checkmark.circle.fill")
                            .font(.system(size: 13))
                            .foregroundStyle(Color.teal)
                            .padding(.top, 2)
                        Text(rec)
                            .font(.system(size: 13))
                            .foregroundStyle(Color.ink)
                    }
                    .padding(12)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(Color.cream.opacity(0.6))
                    .clipShape(RoundedRectangle(cornerRadius: 12))
                }
            }
        }
    }

    // Decorative actions, per spec §2
    private var shareButtons: some View {
        HStack(spacing: 12) {
            Label("Send to doctor", systemImage: "square.and.arrow.up")
                .font(.system(size: 14, weight: .bold))
                .foregroundStyle(Color.ink)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
                .background(Color.lime)
                .clipShape(RoundedRectangle(cornerRadius: 14))
            Label("Download PDF", systemImage: "arrow.down.doc")
                .font(.system(size: 14, weight: .bold))
                .foregroundStyle(Color.ink)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
                .background(Color.white)
                .overlay(RoundedRectangle(cornerRadius: 14).strokeBorder(Color.ink.opacity(0.1), lineWidth: 1))
                .clipShape(RoundedRectangle(cornerRadius: 14))
        }
    }

    private func amplitudeColor(_ a: Double) -> Color {
        a > 3 ? .coral : a > 2 ? .gold : .teal
    }
}

private struct MetricCard: View {
    let label: String
    let value: String
    let highlight: Bool
    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(label)
                .font(.system(size: 11))
                .foregroundStyle(Color.muted)
            Text(value)
                .font(.system(size: 17, weight: .heavy))
                .foregroundStyle(highlight ? Color.limeDark : Color.ink)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(14)
        .background(Color.white)
        .overlay(RoundedRectangle(cornerRadius: 20).strokeBorder(highlight ? Color.lime.opacity(0.3) : Color.ink.opacity(0.05), lineWidth: 1))
        .clipShape(RoundedRectangle(cornerRadius: 20))
    }
}
